//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace souvenirshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public int ComputerID { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public string RamCapacity { get; set; }
        public string ProcessorTechnology { get; set; }
        public string Monitor_Size { get; set; }
        public int ProductID { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
