//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace souvenirshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SalesID { get; set; }
        public System.DateTime DateofSale { get; set; }
        public int CustomerID { get; set; }
        public int Howmanyproductssold { get; set; }
        public int Ratinginformation { get; set; }
        public int ProductID { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
